name: Publish SDK demo on release

on:
  workflow_dispatch:
  push:
    tags:
      - 'releases/sdk/**'
      - '!releases/sdk/**-beta*'
      - '!releases/sdk/**-alpha*'

jobs:
  push_sdk_demo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Build SDK Demo
        run:  npx lerna run build --scope '@meeco/{style-kit,sdk-demo}'
      - name: Deploy SDK Demo GH page
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SDK_DOCS_DEPLOY_KEY }}
          publish_dir: ./docs/sdk-demo
          destination_dir: sdk-demo
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          external_repository: Meeco/sdk-docs
          publish_branch: master
